spring.application.name=sales_be

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=sales

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-part-count=30

spring.main.allow-circular-references=true

server.address=0.0.0.0
server.port=8081

server.ssl.enabled=false
# server.ssl.key-store=file:D:/Project internal/chung chi/homepage.p12
# server.ssl.key-store-password=123456
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=homepage

server.forward-headers-strategy=framework